apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 50-infra-dummyfile
  labels:
    machineconfiguration.openshift.io/role: infra
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
        - path: /etc/dummyfile.conf
          filesystem: root
          contents:
            source: data:text/plain;charset=utf-8;base64,SSBhbSBhbiBpbmZyYQo=
          mode: 0644
          user:
            name: root
          group:
            name: root
