apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: certified-operators-disconnected
  namespace: openshift-marketplace
spec:
  displayName: Certified Operators (Disconnected)
  image: registry.ocp.bmlab.int:5000/olm/certified-operators:v4.4-v1
  sourceType: grpc
  publisher: Manual
