apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: certified-operators-disconnected
  namespace: openshift-marketplace
spec:
  displayName: Certified Operators (Disconnected)
  image: registry.ocp.bmlab.int:5000/olm/certified-operator-index:v4.6-v1
  sourceType: grpc
  publisher: Disconnected
updateStrategy:
  registryPoll: 
    interval: 8h
