= Openshift 4

Deploy Openshift 4 on libvirt using Terraform without Internet access.

image::assets/architecture.svg[align="center", Openshift 4 disconnected architecture]

== Minimum hardware requirements

The minimun requirements allow to deploy a 3 master/worker nodes cluster.

- RAM 32GB
- vCPU 12
- Storage 300GB

== Software requirements

- Libvirt 5.6.0+
- Terraform 0.12.26+
- Libvirt provider for Terraform 0.6.2+
- Openshift client 4.4+
- FCCT 0.5.0+
- UnZip 6.00+
- YQ parser 3.3.2+

=== Install libvirt

Install libvirt following https://docs.fedoraproject.org/en-US/quick-docs/getting-started-with-virtualization/index.html[official documentacion].

=== Install requirements

The `+requirements.sh+` will install all needed requirements.

[source,bash]
----
make require
----

== Setup Libvirt

Add your user to the `+libvirt+` group.

[source,bash]
----
usermod -a -G libvirt maintuser
----

Use `+virsh+` command utility to configure libvirt.

[source,bash]
----
export LIBVIRT_DEFAULT_URI="qemu:///system"
----

Check if libvirt is running.

[source,bash]
----
virsh version --daemon
----

=== QEMU permissions

The provider does not currently support to create volumes with different mode than `+root:root+` so QEMU agent must run as priviledged.

[source,bash]
----
sed -i '/^#user/s/^#//' /etc/libvirt/qemu.conf
sed -i '/^#group/s/^#//' /etc/libvirt/qemu.conf
----

Restart libvirt daemon.

[source,bash]
----
systemctl restart libvirtd
----

== Deploy cluster

Get your pull secret from cloud.redhat.com and copy it to the `+pull-secret.json+` file. Export the pull secret as a Terraform variable.

[source,bash]
----
export TF_VAR_OCP_PULL_SECRET="$(cat pull-secret.json)"
----

Deploy Openshift cluster.

[source,bash]
----
make
----

Mirror the Openshift registry (change OCP_VERSION value).

[source,bash]
----
export OCP_VERSION="x.y.z-arch"

./upload-mirror-images.sh \
    registry.ocp.bmlab.int:5000/ocp4/release ${OCP_VERSION} src/registry/pull-secret.json
----

Power on `+bootstrap+` node.

[source,bash]
----
virsh start ocp-bootstrap
----

Wait until bootstrap is up and running to power on master nodes.

[source,bash]
----
for i in $(seq 0 2); do
    virsh start "ocp-master0$i"
done
----

Wait until master nodes are up and running to power on worker nodes.

[source,bash]
----
for i in $(seq 0 2); do
    virsh start "ocp-worker0$i"
done
----

Approve all pending CSR to allow nodes registration (run the command twice to ensure that all certificates are signed).

[source,bash]
----
export KUBECONFIG="src/ignition/openshift/localhost/auth/kubeconfig"
for run in $(seq 0 1); do
    oc get csr \
        -o go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}' |\
            xargs oc adm certificate approve
    sleep 10
done
----

Verify the Openshift cluster is correctly created.

[source,bash]
----
oc get nodes
----

Add `+node-role.kubernetes.io/infra+` label to worker nodes.

[source,bash]
----
for i in $(seq 0 2); do
    oc label node "worker0$i" node-role.kubernetes.io/infra=""
done
----

Scale to 3 replicas and move the `+default ingress controller+` to infra nodes.

[source,bash]
----
oc apply -f src/ingress
----

Finally, shutdown the bootstrap node.

[source,bash]
----
virsh shutdown ocp-bootstrap
----

=== Enable OLM

Mirror the operators catalog.

[source,bash]
----
export OCP_VERSION="x.y.z-arch"

./upload-operator-catalog.sh \
    registry.ocp.bmlab.int:5000 ${OCP_VERSION} src/registry/pull-secret.json
----

IMPORTANT: This process will take up to 10 hours and needs ~100GB, be patient.

=== Samples operator

Disable samples operator.

[source,bash]
----
oc patch configs.samples cluster \
    --type=merge --patch '{"spec":{"managementState":"Removed"}}'
----

=== Openshift registry

Disable internal Openshift registry.

[source,bash]
----
oc patch configs.imageregistr cluster \
    --type=merge --patch '{"spec":{"managementState":"Removed"}}'
----

=== Upgrade cluster

Mirror the Openshift registry with the new version images.

[source,bash]
----
export UPGRADE_TO="x.y.z-arch"

./upload-mirror-images.sh \
    registry.ocp.bmlab.int:5000/ocp4/release ${UPGRADE_TO} src/registry/pull-secret.json
----

Get the digest for the new version.

[source,bash]
----
oc adm release info \
    quay.io/openshift-release-dev/ocp-release:${UPGRADE_TO} | grep "Pull From:"
Pull From: quay.io/openshift-release-dev/ocp-release@${UPGRADE_DIGEST}
----

Upgrade to the desired version.

[source,bash]
----
oc adm upgrade \
    --force \
    --allow-explicit-upgrade \
    --to-image=registry.ocp.bmlab.int:5000/ocp4/release@${UPGRADE_DIGEST}
----

== References

- https://docs.openshift.com/container-platform/4.4/welcome/index.html
- https://docs.openshift.com/container-platform/4.4/operators/olm-restricted-networks.html
