= Openshift 4

Deploy Openshift 4 on libvirt using Terraform without Internet access.

image::assets/architecture.svg[align="center", Openshift 4 disconnected architecture]

== Requirements

=== Hardware

The minimun requirements allow to deploy a 3 master/worker nodes cluster.

- RAM 32GB
- vCPU 12
- Storage 300GB

=== Software

- Libvirt 5.6.0+
- Terraform 0.12.26+
- Libvirt provider for Terraform 0.6.2+
- Openshift client 4.4+
- FCCT 0.5.0+
- UnZip 6.00+
- YQ parser 3.3.2+

=== Install requirements

The `+requirements.sh+` script will install all needed requirements.

[source,bash]
----
make require
----

==== Setup Libvirt

Install libvirt following https://docs.fedoraproject.org/en-US/quick-docs/getting-started-with-virtualization/index.html[official documentacion].

Add your user to the `+libvirt+` group.

[source,bash]
----
usermod -a -G libvirt maintuser
----

Use `+virsh+` command utility to configure libvirt.

[source,bash]
----
export LIBVIRT_DEFAULT_URI="qemu:///system"
----

Check if libvirt is running.

[source,bash]
----
virsh version --daemon
----

==== QEMU permissions

The provider does not currently support to create volumes with different mode than `+root:root+` so QEMU agent must run as priviledged.

[source,bash]
----
sed -i '/^#user/s/^#//' /etc/libvirt/qemu.conf
sed -i '/^#group/s/^#//' /etc/libvirt/qemu.conf
----

Restart libvirt daemon.

[source,bash]
----
systemctl restart libvirtd
----

==== Download pull secret

Get your pull secret from `+cloud.redhat.com+` and copy it to the `+src/openshift-install/${OCP_ENVIRONMENT}+` folder (create the folder for your environment if it does not exist).

[source,bash]
----
src/ocp
 ├── dev
 │   └── pull-secret.json
 ├── pre
 │   └── pull-secret.json
 └── pro
     └── pull-secret.json
----

== Install Openshift 4

Deploy Openshift 4 cluster.

[source,bash]
----
make
----

=== Mirror registry (disconnected)

Mirror the images used during the installation to the external registry.

[source,bash]
----
./output/openshift-install/${OCP_ENVIRONMENT}/mirror-release-image.sh
----

=== Bootstrap

Power on `+bootstrap+` node.

[source,bash]
----
virsh start ocp-bootstrap
----

=== Control plane

Wait until bootstrap is up and running to power on master nodes.

[source,bash]
----
for i in $(seq 0 2); do virsh start "ocp-master0$i"; done
----

=== Worker nodes

Wait until master nodes are up and running to power on worker nodes.

[source,bash]
----
for i in $(seq 0 2); do virsh start "ocp-worker0$i"; done
----

Approve all pending CSR to allow nodes registration (run the command twice to ensure that all certificates are signed).

[source,bash]
----
export KUBECONFIG="$(pwd)/output/openshift-install/localhost/auth/kubeconfig"
for run in $(seq 0 1); do
    oc get csr \
        -o go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}' |\
            xargs oc adm certificate approve
    sleep 10
done
----

Verify the Openshift cluster is correctly created.

[source,bash]
----
oc get nodes
----

=== Destroy bootstrap node

Finally, shutdown the bootstrap node.

[source,bash]
----
virsh shutdown ocp-bootstrap
----

== Day-2 operations

Once Openshift 4 has been deployed in can be configured with the instructions in `+day-two+` folder resources.

== References

- https://docs.openshift.com/container-platform/4.4/welcome/index.html
