---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: Local authentication
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: oauth-htpasswd
