apiVersion: v1
kind: Pod
metadata:
  name: large-pod
  labels:
    app: cluster-capacity
    component: pod-spec
    size: large
spec:
  containers:
  - name: application
    image: registry.redhat.io/ubi8/ubi-minimal:8.2
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "1"
        memory: "1Gi"

