apiVersion: v1
kind: Pod
metadata:
  name: small-pod
  labels:
    app: cluster-capacity
    component: pod-spec
    size: small
spec:
  containers:
  - name: application
    image: registry.redhat.io/ubi8/ubi-minimal:8.2
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi

