apiVersion: v1
kind: Pod
metadata:
  name: xlarge-pod
  labels:
    app: cluster-capacity
    component: pod-spec
    size: xlarge
spec:
  containers:
  - name: application
    image: registry.redhat.io/ubi8/ubi-minimal:8.2
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "2"
        memory: "8Gi"
      requests:
        cpu: "2"
        memory: "8Gi"

