apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: openshift-testing
  labels:
    application: example
spec:
  replicas: 2
  strategy:
    type: RollingUpdate # Or Recreate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      application: example
  template:
    metadata:
      labels:
        application: example
    spec:
      containers:
        - name: container-one
          image: ubi8/ubi-minimal:8.1-407
          imagePullPolicy: IfNotPresent
          entrypoint: sh
          command:
            - sleep
            - "3600"
