---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: stress-hostport
  namespace: openshift-ingress-operator
spec:
  replicas: 1
  domain: stress-hostport.bmlab.int
  routeSelector:
    matchLabels:
      routerName: stress-hostport
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/perf: ""
  endpointPublishingStrategy:
    type: HostNetwork
