apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: grafana-operator
spec:
  name: grafana-operator
  channel: alpha
  installPlanApproval: Automatic
  source: community-operators-disconnected
  sourceNamespace: openshift-marketplace
