apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators-disconnected
  namespace: openshift-marketplace
spec:
  displayName: Red Hat Operators (Disconnected)
  image: registry.ocp.bmlab.int:5000/olm/redhat-operators:v4.4-v1
  sourceType: grpc
  publisher: Manual
