apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: public-instance
  namespace: grafana-operator
  labels:
    app: grafana-operator
    component: public
spec:
  ingress:
    enabled: true
  config:
    auth:
      disable_signout_menu: false
    auth.anonymous:
      enabled: false
    log:
      level: warn
      mode: console
    security:
      admin_user: admin
      admin_password: CHANGE_ME
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
