global:
  resolve_timeout: 5m
receivers:
  - name: default
    webhook_configs:
      - url: "http://http-logger.openshift-monitoring.svc:8080"
        send_resolved: true
        http_config:
          basic_auth:
            username: example
            password: s3cr3t
  - name: watchdog
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 30s
  receiver: default
  routes:
    - match:
        alertname: Watchdog
      repeat_interval: 5m
      receiver: watchdog

