---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-logger
  labels:
    app: alertmanager
    component: http-logger
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: alertmanager
      component: http-logger
  template:
    metadata:
      labels:
        app: alertmanager
        component: http-logger
    spec:
      serviceAccountName: http-logger
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: http-server
          image: docker.io/mendhak/http-https-echo:17
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: http-logger
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: alertmanager
    component: http-logger

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: http-logger
  labels:
    app: alertmanager
    component: http-logger

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-nonroot-scc
  labels:
    app: alertmanager
    component: http-logger
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - nonroot

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: http-logger-sa-nonroot
  labels:
    app: alertmanager
    component: http-logger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-nonroot-scc
subjects:
  - kind: ServiceAccount
    name: http-logger

