---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: example
  labels:
    app: example
spec:
  replicas: 1
  selector:
    app: example
  stratey:
    type: Rolling
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: loop
          image: registry.ocp.bmlab.int:5000/ubi8/ubi-minimal:8.2
          command: [ "/bin/bash", "-c" ]
          args: [ "while true; do echo $(date); sleep 30; done;" ]
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
