---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-backup-files 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteMany
  nfs: 
    path: /etcd-backup 
    server: helper.ocp.bmlab.int
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup-files
spec:
  storageClass: ""
  volumeName: etcd-backup-files
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
