= Cluster Monitoring Operator (CMO)

The Cluster Monitoring Operator (CMO) is a central component of the monitoring stack. It deploys and manages Prometheus instances, Grafana, Alertmanager, the Thanos Querier, the Telemeter Client and metrics targets and ensures that they are up to date.

== Configuration

The cluster-monitoring-config `+ConfigMap+` configures how the stack is deployed.

[source,yaml]
----
include::cmo/cluster-monitoring-config.yml[]
----

Configure the stack by using the `+oc apply+` command on this file.

[source,bash]
----
oc apply -f cmo/cluster-monitoring-config.yml
----

=== Alertmanager

Deploy an HTTP server to receive the alerts from Alertmanager.

[source,bash]
----
oc apply -f cmo/alertmanager/deploy-receiver.yml -n openshift-monitoring
----

Configure Alertmanager to send alerts to this remote receiver.

[source,yaml]
----
include::cmo/alertmanager/config.yml[]
----

The Alertmanager configuration can be updated replacing the content of the alertmanager-main `+Secret+`.

[source,bash]
----
oc create secret generic alertmanager-main \
    --from-file=alertmanager.yaml=cmo/alertmanager/config.yml --dry-run -o=yaml  -n openshift-monitoring |\
        oc replace secret --filename=- -n openshift-monitoring
----

Check if the alerts are being processed by the receiver.

[source,bash]
----
oc logs -l component=webhook-receiver -n openshift-monitoring -f
----

== Grafana Operator

Install `+Grafana Operator+` from Openshift marketplace.

[source,bash]
----
oc apply -f grafana-operator/
----

Deploy a `+Grafana+` instance.

[source,bash]
----
oc apply -f grafana-operator/instances/public.yml
----

Create a `+ServiceAccount+` to allow Grafana to read metrics from Prometheus.

[source,bash]
----
oc apply -f grafana-operator/datasources/00-prometheus-rbac.yml
----

Retrieve credentials from this  `+ServiceAccount+`.

[source,bash]
----
SA_TOKEN_NAME=$(oc get sa prometheus-reader -o jsonpath='{range .secrets[*]}{.name}{"\n"}{end}' | grep token)
export PROMETHEUS_TOKEN=$(oc get secret $token_name -o jsonpath='{.data.token}' | base64 -d)
----

Create a `+GrafanaDataSource+` to read metrics from Thanos.

[source,bash]
----
envsubst < grafana-operator/datasources/01-prometheus.yml.tpl | oc apply -f -
----

Create multiple `+GrafanaDashboard+` to visualize metrics.

[source,bash]
----
oc apply -f grafana-operator/dashboards
----

[source,bash]

== References

- https://github.com/openshift/cluster-monitoring-operator
