---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-backup-files
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /etcd-backup
    server: helper.ocp.bmlab.int
  persistentVolumeReclaimPolicy: Retain
